### ISSUE TITLE
helm: add pathType for ingress

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#79]
https://github.com/threefoldtech/tfgrid_dashboard/blob/v1.0.2/charts/tfgrid-dashboard/values.yaml

The value.yaml file was used as a template for deploying with Helm. The ingress type lacks a pathType which seems to be required by the helm template files. It gave this error:

`Error: UPGRADE FAILED: failed to create resource: Ingress.extensions "tfgrid-dashboard" is invalid: spec.rules[0].http.paths[0].pathType: Required value: pathType must be specified`

Should be added like this

```
ingress:
  enabled: true
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt
  hosts:
    - host: dashbard.com
      paths:
        - path: /
          pathType: Prefix
  tls:
    - secretName: chart-example-tls
      hosts:
        - dashbard.com
```
