### ISSUE TITLE
helm: change ServiceAccount name

### ISSUE THREAD

**Issue by coesensbert** [threefoldtecharchive/tfgrid_dashboard#80]
https://github.com/threefoldtech/tfgrid_dashboard/blob/v1.0.2/charts/tfgrid-dashboard/values.yaml

The value.yaml file was used as a template for deploying with Helm. It gave the following error:

`Error: INSTALLATION FAILED: ServiceAccount "tfgrid_dashboard" is invalid: metadata.name: Invalid value: "tfgrid_dashboard": a lowercase RFC 1123 subdomain must consist of lower case alphanumeric characters, '-' or '.', and must start and end with an alphanumeric character (e.g. 'example.com', regex used for validation is '[a-z0-9]([-a-z0-9]*[a-z0-9])?(\.[a-z0-9]([-a-z0-9]*[a-z0-9])?)*')`

For deployment on devnet we changed _ to -

```
serviceAccount:
  # Specifies whether a service account should be created
  create: true
  # Annotations to add to the service account
  annotations: {}
  # The name of the service account to use.
  # If not set and create is true, a name is generated using the fullname template
  name: "tfgrid-dashboard"
```
